####Task 3.1: NumPy Basics





In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(1,101,10)
a

array([35, 92, 67, 43, 16,  7, 14, 30, 61, 25])

In [24]:
np.max(a)


np.int64(92)

In [26]:
np.min(a,axis = 0)

np.int64(7)

In [27]:
np.mean(a)

np.float64(39.0)

In [28]:
np.sum(a)

np.int64(390)

In [30]:
np.argmax(a)

np.int64(1)

In [31]:
np.argmin(a)

np.int64(5)

In [32]:
np.sort(a)

array([ 7, 14, 16, 25, 30, 35, 43, 61, 67, 92])

####: NumPy Indexing and Slicing

In [33]:
b = np.random.randint(1,21, size = (3,3))
b

array([[ 7, 18, 17],
       [ 3,  8, 19],
       [18,  8, 14]])

In [34]:
b[0]

array([ 7, 18, 17])

In [36]:
b[:,1]

array([18,  8,  8])

In [37]:
b[2,2]

np.int64(14)

In [39]:
b[:2,:2]

array([[ 7, 18],
       [ 3,  8]])

In [41]:
b[1,1]=99
b

array([[ 7, 18, 17],
       [ 3, 99, 19],
       [18,  8, 14]])

####Task 3.3: NumPy Vectorized Operations

In [43]:
n1 = np.random.randint(1,21,10)
n2 = np.random.randint(1,21,10)
print(n1)
print(n2)

[17 18  7  9  3  1 12 12 11  2]
[ 5  2  3  5 14 11  1 17 12 10]


In [44]:
n1+n2

array([22, 20, 10, 14, 17, 12, 13, 29, 23, 12])

In [45]:
n1-n2

array([ 12,  16,   4,   4, -11, -10,  11,  -5,  -1,  -8])

In [46]:
n1*n2

array([ 85,  36,  21,  45,  42,  11,  12, 204, 132,  20])

In [47]:
n1/n2

array([ 3.4       ,  9.        ,  2.33333333,  1.8       ,  0.21428571,
        0.09090909, 12.        ,  0.70588235,  0.91666667,  0.2       ])

In [48]:
n1**2

array([289, 324,  49,  81,   9,   1, 144, 144, 121,   4])

In [49]:
np.dot(n1,n2)

np.int64(608)

In [50]:
np.sort(n2)

array([ 1,  2,  3,  5,  5, 10, 11, 12, 14, 17])